### ISSUE TITLE
Help with using multiple pages

### ISSUE THREAD

**Issue by erik73** [kdorff/esphome#2]
Hi, and thanks for the great work with esphome-display-panel!

I use it a lot, and find it very easy to use.

Now I am experimenting with display pages, and as a starting point I used the following example code you have provided in tft-office. I think I understand how to use the int pageNumber to do what I want, but I fail to add the panels I want to use in the following vector:

`std::vector<std::vector<DisplayPanel*>> pages = {
    {
        // Page 0. The only page at the moment.
        &contDownPanel,
        &datePanel,
        &dayPanel,
        &contUpPanel,
        &timePanel,
        &insideTempPanel,
        &insideLabelPanel,
        &outdoorLabelPanel,
        &outdoorTempPanel,
        &butterflyPanel
    }
};`

As I understand it, the objects above is stored in the vector pages[0].
How would the code look to insert another list of panels inte the next available position pages[1]?

My C++ is at a beginner level and I don´t understand the vector created here...

I would really appreciate your help with this.

**Comment by kdorff** [comment]
As part of this video https://www.youtube.com/watch?v=VQ3LSnCgpeE ResinChem Tech used multiple pages in one of his projects. See his `.h` file within

https://github.com/Resinchem/Arylic-Amp-MQTT/tree/main/sirius-tft-touch-add-on

Hopefully that helps.
Kevin

**Comment by erik73** [comment]
Thanks!

That got me in the right direction.

Now, I can do even more with my displays. Great, and once again, thanks!
