### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by PaulBiod** [kdorff/esphome#3]
Hi @kdorff ,
Trying out your code, I get some error while compiling.

In my main file, I have : 

![image](https://github.com/kdorff/esphome/assets/28720176/e60fc609-0e43-4703-a05c-cfd5e511835d)

And the tft-room-time-temp.h is your original file, I put it on the esphome directory.
And the result is : 

![image](https://github.com/kdorff/esphome/assets/28720176/cc38f2d2-20fc-4677-91b1-e3ffb74967a8)

![image](https://github.com/kdorff/esphome/assets/28720176/220c5db1-485b-4b49-a1ac-f576c256991d)

![image](https://github.com/kdorff/esphome/assets/28720176/f0ddb5ea-a01f-402e-959c-2cef1697b636)

![image](https://github.com/kdorff/esphome/assets/28720176/ce0cf164-4e5f-440a-9240-b8b80a386ad9)

![image](https://github.com/kdorff/esphome/assets/28720176/2f02e6cd-5c50-4eca-9187-cce01f6b3aeb)

![image](https://github.com/kdorff/esphome/assets/28720176/fa2fdba1-c9d9-4de3-88c3-be5dff17cd9a)

**Comment by kdorff** [comment]
I'm not clear which source you were starting with, but I updated several of my projects for `esphome-display-panel.git#v0.0.14` which is now necessary. You can see the changes I pushed which will probably help you update your code.

https://github.com/kdorff/esphome/commit/69a51b246bec2ee88e54f04d249369c5933c8273

**Comment by PaulBiod** [comment]
> I'm not clear which source you were starting with, but I updated several of my projects for `esphome-display-panel.git#v0.0.14` which is now necessary. You can see the changes I pushed which will probably help you update your code.
> 
> [69a51b2](https://github.com/kdorff/esphome/commit/69a51b246bec2ee88e54f04d249369c5933c8273)

Hi @kdorff 
Thanks for the reply.
I used the files tft-office.yaml and tft-room-time-temp.h
I applied the fixes (and cleaned built files), now it's way better, but still some errors : 

![image](https://github.com/kdorff/esphome/assets/28720176/954cefa1-223a-4abb-a7e7-c4b245d1b680)

![image](https://github.com/kdorff/esphome/assets/28720176/f6ece247-3d71-484c-a60d-c3da5d5a06a0)

It's related to those lines : 

![image](https://github.com/kdorff/esphome/assets/28720176/b10c75c5-0dc5-439f-899c-8944523c52dd)

Also, I saw you are using old  'swap_x_y: false' which should be 

'transform:
    mirror_x: false
    mirror_y: true
    swap_xy: false'

and report_interval which is not used anymore

Thanks

**Comment by PaulBiod** [comment]
Ok, solved it.
In tft-office.yaml you have to changed all 'id(touchid).x' to 'touch.x' and now it works
The same for x_raw, y_raw => touch.x_raw

**Comment by kdorff** [comment]
Nice.
