### ISSUE TITLE
[ QUESTION ]

### ISSUE THREAD

**Issue by PaulBiod** [kdorff/esphome#4]
Hi,
In my page, let's say I have a panel that prints an icon and a text (example : temperature icon with temperature value).
The panel is like : 

`barreHautGauchePanel.font = icon_font_45;`

And then, later, I have 

`if (interieur->has_state()) {
            // Temperature
            sprintf(buffer, "%.1f°", interieur->state);
            barreHautGauchePanel.text = { buffer };
        }`
        
But as the panel has the icon font, obviously the text won't show up. Is there a way to change the text font without having to create separate panels for icons and text ?
Thanks

**Comment by kdorff** [comment]
Panels can have one font.  You have options

1. **Best Advice. Read this one and take it to heart** Pick a font that has the symbol. Most fonts should have the "°" symbol as it's a very common symbol. My font choice has no issues showing both text and symbols. 
```
font:
  - file: "gfonts://Rubik@800"
    id: font_temp
    size: 70
```
2. Create more panels, as you mentioned. Sounds like a pain but will take you 10 minutes. \<snark\>But really? There isn't a font, out of the tens of thousands of fonts out there, you like that has the symbol? \</snark\>
3. \<not-quite-snark\>Fork my code and figure out how to support multiple fonts in a panel.\</not-quite-snark\> It doesn't currently support this and I feel like it would make the configuration messy. I don't any drive to implement this feature. I'll refer to you options 1 or 2.

**Comment by PaulBiod** [comment]
Hi @kdorff 
I wasn't talking about the "°", was talking about an icon like on this photo, so, solution 1 isn't ok. Anyway, thanks for giving me a direction, I guess option 2 will be the easiest.
Thanks
![20240207_154127](https://github.com/kdorff/esphome/assets/28720176/e67d7651-7185-4a68-83c3-5fdd713ec977)
